// stream actions
export const START_LOADING_STREAMS = 'START_LOADING_STREAMS';
export const FAILED_LOADING_STREAMS = 'FAILED_LOADING_STREAMS';
export const SUCCESSFULLY_FETCHED_STREAMS = 'SUCCESSFULLY_FETCHED_STREAMS';

export const START_LOADING_STREAM = 'START_LOADING_STREAM';
export const FAILED_LOADING_STREAM = 'FAILED_LOADING_STREAM';
export const SUCCESSFULLY_FETCHED_STREAM = 'SUCCESSFULLY_FETCHED_STREAM';

export const SUCCESSFULLY_CREATED_STREAM = 'SUCCESSFULLY_CREATED_STREAM';
export const SUCCESSFULLY_REMOVED_STREAM = 'SUCCESSFULLY_REMOVED_STREAM';


// user actions
export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

//google auth
export const SIGNED_IN = "SIGNED_IN";
export const SIGNED_OUT = "SIGNED_OUT"




