// stream actions
export const START_LOADING_STREAMS = 'START_LOADING_STREAMS';
export const FAILED_LOADING_STREAMS = 'FAILED_LOADING_STREAMS';
export const SUCCESSFULLY_LOADED_STREAMS = 'SUCCESSFULLY_LOADED_STREAMS';

export const START_LOADING_STREAM = 'START_LOADING_STREAM';
export const FAILED_LOADING_STREAM = 'FAILED_LOADING_STREAM';
export const SUCCESSFULLY_LOADED_STREAM = 'SUCCESSFULLY_LOADED_STREAM';

export const SUCCESSFULLY_ADDED_STREAM = 'SUCCESSFULLY_ADDED_STREAM';
export const SUCCESSFULLY_REMOVED_STREAM = 'SUCCESSFULLY_REMOVED_STREAM';


// user actions
export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';






