// stream actions
export const SUCCESSFULLY_LOADED_STREAMS = 'SUCCESSFULLY_LOADED_STREAMS';
export const START_LOADING_STREAMS = 'START_LOADING_STREAMS';
export const FAILED_LOADING_STREAMS = 'FAILED_LOADING_STREAMS';
export const SUCCESSFULLY_ADDED_STREAM = 'SUCCESSFULLY_ADDED_STREAM';

